name: Leetcode Problem Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Restart PM2 Service
        run: |
          cd ~/leetcode-problem-service
          git pull origin main
          npm ci
          pm2 restart leetcode-problem-service || pm2 start src/index.js --name leetcode-problem-service
